name: haskell-playground
version: '0.1.0.0'
category: Web
author: Lukwago Allan
maintainer: epicallan.al@gmail.com
copyright: 2017 Lukwago Allan
license: BSD3
github: epicallan/haskell-playground
extra-source-files:
- README.md
library:
  source-dirs: src
  dependencies:
  - aeson
  - async
  - base
  - classy-prelude-conduit
  - bytestring
  - conduit
  - containers
  - directory
  - filepath
  - lens
  - mtl
  - megaparsec
  - protolude
  - singletons
  - universum
  - tagged
  - template-haskell
  - temporary
  - text
  - time
  - vinyl
default-extensions:
  - LambdaCase
  - DeriveGeneric
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - TypeApplications
  - MultiParamTypeClasses
  - RecordWildCards
  - TypeApplications
  - TypeFamilies
  - GADTs
  - PolyKinds
  - DataKinds
  - UndecidableInstances
  - KindSignatures
