name: haskell-playground
version: '0.1.0.0'
category: Web
author: Lukwago Allan
maintainer: epicallan.al@gmail.com
copyright: 2017 Lukwago Allan
license: BSD3
github: epicallan/haskell-playground
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Json
  - TypeFamilies
  - Lenses
  - TypeFamiliesWiki
  dependencies:
  - aeson
  - base
  - bytestring
  - conduit
  - containers
  - lens
  - text





tests:
  haskell-playground-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - haskell-playground
