name: haskell-playground
version: '0.1.0.0'
category: Web
author: Lukwago Allan
maintainer: epicallan.al@gmail.com
copyright: 2017 Lukwago Allan
license: BSD3
github: epicallan/haskell-playground
extra-source-files:
- README.md
library:
  source-dirs: src
  dependencies:
  - aeson
  - async
  - base
  - classy-prelude-conduit
  - bytestring
  - conduit
  - conduit-extra
  - containers
  - directory
  - filepath
  - finite-typelits
  - ghc-prim
  - ghc-typelits-natnormalise
  - lens
  - mtl
  - megaparsec
  - protolude
  - singletons
  - resourcet
  - universum
  - tagged
  - template-haskell
  - temporary
  - text
  - time
  - vector
  - vinyl
default-extensions:
  - LambdaCase
  - DeriveGeneric
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - TypeApplications
  - MultiParamTypeClasses
  - RecordWildCards
  - TypeApplications
  - TypeFamilies
  - GADTs
  - FunctionalDependencies
  - PolyKinds
  - DataKinds
  - RankNTypes
  - TemplateHaskell
  - TypeOperators
  - UndecidableInstances
  - KindSignatures

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -fhide-source-paths
  - -Wpartial-fields
