name: haskell-playground
version: '0.1.0.0'
category: Web
author: Lukwago Allan
maintainer: epicallan.al@gmail.com
copyright: 2017 Lukwago Allan
license: BSD3
github: epicallan/haskell-playground
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Json
  - Lenses
  dependencies:
  - aeson
  - async
  - base
  - classy-prelude-conduit
  - bytestring
  - conduit
  - containers
  - lens
  - megaparsec
  - protolude
  - text
  - tagged
